name: Library Tests

on:
  push:
    branches:
      - 'master'
      - 'dev'
    paths:
      - 'valorant/**'
  pull_request:
    branches:
      - 'master'
      - 'dev'
    types: [opened, reopened, synchronize, ready_for_review, review_requested]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VALPY_KEY: ${{ secrets.VALPY_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python v3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install missing dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests
      - name: Run library tests
        run: python -m tests
